# fly.toml app configuration file generated for yral-auth-v2-staging on 2025-06-11T12:38:33+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yral-auth-v2-staging'
primary_region = 'sin'

[build]

[env]
  APPLE_CLIENT_ID = 'com.yral.yral-auth'
  APPLE_KEY_ID = '9DWVYWDYD8'
  APPLE_TEAM_ID = '2UL556KNXC'
  CLIENT_JWT_PUB_ED_PEM = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAKpZNfPOONR9AXiaGmHv8AHemm4SNK0uh+mf523ho5KU=\n-----END PUBLIC KEY-----"
  GOOGLE_CLIENT_ID = '804814798298-taifmq3k6olk9bjr1cqb9gfnp1mssqqb.apps.googleusercontent.com'
  JWT_PUB_EC_PEM = "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoqN3/0RNfrnrnYGxKBgy/qHnmITr\n+6ucjxStx7tjA30QJZlWzo0atxmY8y9dUR+eKQI0SnbQds4xLEU8+JGm8Q==\n-----END PUBLIC KEY-----"
  PORT = '8080'
  SERVER_URL = 'https://yral-auth-v2-staging.fly.dev/'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
