on:
  workflow_dispatch:
  push:
    branches:
      - naitik/coolify-and-vault-integration

permissions:
  id-token: write   
  contents: read

jobs:
  upload-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.yral.com
          method: jwt
          role: yral-auth-v2-write-role
          jwtGithubAudience: "https://github.com/dolr-ai"
          exportToken: true

      - name: Install Vault CLI
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault

      - name: Set Secrets
        env:
          VAULT_ADDR: https://vault.yral.com
          AUTH_SESSION_COOKIE_SIGNING_SECRET_KEY: ${{ secrets.AUTH_SESSION_COOKIE_SIGNING_SECRET_KEY }}
          GOOGLE_SIGNING_OAUTH_CLIENT_CREDENTIAL_CLIENT_SECRET: ${{ secrets.GOOGLE_SIGNING_OAUTH_CLIENT_CREDENTIAL_CLIENT_SECRET }}
          AUTH_JWT_ES256_SIGNING_SECRET_KEY_PEM: ${{ secrets.AUTH_JWT_ES256_SIGNING_SECRET_KEY_PEM }}
          CLIENT_JWT_ED_PEM: ${{ secrets.CLIENT_JWT_ED_PEM }}
          APPLE_AUTH_KEY_PEM: ${{ secrets.APPLE_AUTH_KEY_PEM }}
          WHATAPP_MESSAGE_SERVICE_API_KEY: ${{ secrets.WHATAPP_MESSAGE_SERVICE_API_KEY }}
        run: |
          vault kv put secret/yral-auth-v2/AUTH_SESSION_COOKIE_SIGNING_SECRET_KEY value="$AUTH_SESSION_COOKIE_SIGNING_SECRET_KEY"
          vault kv put secret/yral-auth-v2/GOOGLE_SIGNING_OAUTH_CLIENT_CREDENTIAL_CLIENT_SECRET value="$GOOGLE_SIGNING_OAUTH_CLIENT_CREDENTIAL_CLIENT_SECRET"
          vault kv put secret/yral-auth-v2/AUTH_JWT_ES256_SIGNING_SECRET_KEY_PEM value="$AUTH_JWT_ES256_SIGNING_SECRET_KEY_PEM"
          vault kv put secret/yral-auth-v2/CLIENT_JWT_ED_PEM value="$CLIENT_JWT_ED_PEM"
          vault kv put secret/yral-auth-v2/APPLE_AUTH_KEY_PEM value="$APPLE_AUTH_KEY_PEM"
          vault kv put secret/yral-auth-v2/WHATAPP_MESSAGE_SERVICE_API_KEY value="$WHATAPP_MESSAGE_SERVICE_API_KEY"